### ISSUE TITLE
Practica 7 Conexión de bases de datos

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/conexion-bases-de-datos-equipohjf#3]
[Practica 7 - Heidi Lucy Bautista Sanjuan 4US.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-equipohjf/files/8665775/Practica.7.-.Heidi.Lucy.Bautista.Sanjuan.4US.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
